name: Sync Fork

on:
  schedule:
    - cron: '0 8 */2 * *' # Run this every other day at 8
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: firebase
          base: compose-dev
          head: version-7.2.0-dev